//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetInRoom
    {
        public int AssetInRoomId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> StatusAssetId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Room Room { get; set; }
        public virtual StatusAsset StatusAsset { get; set; }
    }
}
