//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public Asset()
        {
            this.AssetInRooms = new HashSet<AssetInRoom>();
        }
    
        public int AssetId { get; set; }
        public string AssetName { get; set; }
        public string AssetImage { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<AssetInRoom> AssetInRooms { get; set; }
    }
}
