//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestType
    {
        public RequestType()
        {
            this.RequestAssets = new HashSet<RequestAsset>();
        }
    
        public int RequestTypeId { get; set; }
        public string RequestTypeName { get; set; }
        public string IsDeleted { get; set; }
    
        public virtual ICollection<RequestAsset> RequestAssets { get; set; }
    }
}
